---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barinfo
  namespace: demo
  labels:
    app: barinfo
  annotations:
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: barinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: barinfo
    spec:
      initContainers:
      - name: init
        image: alpine:3.10
        command:
        - sleep
        - "1"
      containers:
      - name: barinfod
        image: stefanprodan/podinfo:3.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9890
          protocol: TCP
        - name: http-metrics
          containerPort: 9790
          protocol: TCP
        - name: grpc
          containerPort: 9990
          protocol: TCP
        command:
        - ./podinfo
        - --port=9890
        - --port-metrics=9790
        - --grpc-port=9990
        - --grpc-service-name=barinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9890
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9890
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
